import { test,expect } from '@playwright/test';

test('workspace edits, autosaves, switches templates and exports a PDF',async({page})=>{await page.goto('/');await expect(page.getByRole('button',{name:'All changes saved'})).toBeVisible();await page.getByLabel('First name').fill('Jordan');await expect(page.locator('.paper-header h1')).toHaveText('Jordan Morgan');await expect(page.getByRole('button',{name:'All changes saved'})).toBeVisible();await page.reload();await expect(page.getByLabel('First name')).toHaveValue('Jordan');await page.locator('.template-selector').click();await page.locator('.template-card').filter({has:page.locator('.template-card-label strong',{hasText:'Minimal'})}).click();await expect(page.locator('.template-selector')).toContainText('Minimal');await expect(page.getByLabel('First name')).toHaveValue('Jordan');await page.getByRole('button',{name:'LaTeX Code'}).click();await expect(page.getByLabel('LaTeX source code editor')).toContainText('Jordan Morgan');await page.getByRole('button',{name:'Download',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:/Download PDF/}).click();expect((await download).suggestedFilename()).toMatch(/\.pdf$/);await expect(page.locator('.pdf-frame')).toBeVisible();});

test('LaTeX imports are reviewed, corrected and persisted with original source',async({page})=>{await page.goto('/');await expect(page.getByRole('button',{name:'All changes saved'})).toBeVisible();await page.getByRole('button',{name:/Import LaTeX/}).click();await page.getByRole('button',{name:'Paste LaTeX'}).click();await page.getByLabel('Your existing LaTeX source').fill(String.raw`\documentclass{article}\begin{document}\name{Casey}{Taylor}\email{casey@example.com}\section{Summary}Software engineer with React experience.\section{Skills}React, TypeScript\end{document}`);await page.getByRole('button',{name:'Parse & review'}).click();await expect(page.getByText('A fresh start. Nothing left behind.')).toBeVisible();await page.locator('dialog').getByLabel('First name').fill('Casey');await page.getByRole('button',{name:'Confirm & import resume'}).click();await expect(page.locator('dialog')).not.toBeVisible();await expect(page.getByLabel('First name')).toHaveValue('Casey');await page.reload();await expect(page.getByLabel('First name')).toHaveValue('Casey');await page.getByRole('button',{name:'Download',exact:true}).click();await expect(page.getByRole('button',{name:'Original imported .tex'})).toBeVisible();});

test('version save and restore is real and preserves a backup',async({page})=>{await page.goto('/');await expect(page.getByRole('button',{name:'All changes saved'})).toBeVisible();await page.getByRole('button',{name:'Version history'}).click();await page.getByPlaceholder('Name this version (optional)').fill('First draft');await page.getByRole('button',{name:'Save version',exact:true}).click();await expect(page.locator('.version-item')).toContainText('First draft');await page.getByRole('button',{name:'Close dialog'}).click();await page.getByLabel('First name').fill('Version Two');await expect(page.getByRole('button',{name:'All changes saved'})).toBeVisible();await page.getByRole('button',{name:'Version history'}).click();await page.getByRole('button',{name:'Restore',exact:true}).click();await expect(page.getByLabel('First name')).toHaveValue('Alex');});

test('job analysis is truthful and ATS is labeled heuristic',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'JD analyzer',exact:true}).click();await page.getByLabel('Job description').fill('We need a software engineer to build React and TypeScript applications with Kubernetes. 5+ years of experience.');await page.getByRole('button',{name:'Analyze job description'}).click();await expect(page.locator('.analysis-results')).toContainText('Kubernetes');await expect(page.locator('.suggestion')).toContainText(['Review the skill gaps','Lead with your relevant work']);await page.getByRole('button',{name:'ATS checker',exact:true}).click();await expect(page.getByText('Heuristic readiness score — not a real ATS score')).toBeVisible();});

test('compiler is fail closed and offers an honestly labeled fallback',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Compile',exact:true}).click();await expect(page.getByText('Your source is safe.')).toBeVisible();await expect(page.getByRole('button',{name:'Export form-based PDF'})).toBeVisible();});

test('private workspaces cannot access each other’s resumes',async({browser})=>{const one=await browser.newContext(),two=await browser.newContext();const a=await (await one.request.get('/api/resumes')).json();const b=await (await two.request.get('/api/resumes')).json();expect(a.resumes[0].id).not.toEqual(b.resumes[0].id);const forbidden=await two.request.get('/api/resumes?versions='+a.resumes[0].id);expect(forbidden.status()).toBe(400);await one.close();await two.close();});

test('mobile layout has no horizontal overflow and navigation works',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.getByLabel('First name')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('button',{name:'AI assistant',exact:true}).click();await expect(page.getByText('Find the right words.')).toBeVisible();});
