import { NextResponse } from 'next/server';
import { z } from 'zod';
import { resumeSchema } from '@/lib/resume';
import { ownerSession,readBody,apiError,rateLimit } from '@/lib/server';
import * as service from '@/lib/services/resumeService';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{const owner=await ownerSession();const id=new URL(request.url).searchParams.get('versions');if(id)return NextResponse.json({versions:await service.listVersions(owner,id)});let list=await service.listResumes(owner);if(!list.length)list=[await service.createResume(owner)];return NextResponse.json({resumes:list},{headers:{'Cache-Control':'no-store'}});}catch(e){return apiError(e);}}
const input=z.object({action:z.enum(['create','save','version','restore','delete']),id:z.string().optional(),name:z.string().min(1).max(120).optional(),data:resumeSchema.optional(),template:z.enum(['classic','minimal','engineer','executive','modern','academic']).optional(),tex:z.string().max(250000).nullable().optional(),originalTex:z.string().max(250000).nullable().optional(),versionId:z.string().optional()});
export async function POST(request:Request){try{const owner=await ownerSession();rateLimit(owner+':save',120);const b=input.parse(await readBody(request));if(b.action==='create')return NextResponse.json({resume:await service.createResume(owner,b.name,b.data)});if(!b.id)throw new Error('Resume ID is required.');if(b.action==='save'){if(!b.data)throw new Error('Resume data is required.');return NextResponse.json({resume:await service.saveResume(owner,b.id,{name:b.name||'Untitled resume',data:b.data,template:b.template||'classic',tex:b.tex??null,...(b.originalTex!==undefined?{originalTex:b.originalTex}:{})})});}if(b.action==='version')return NextResponse.json({version:await service.saveVersion(owner,b.id,b.name||'Saved version')});if(b.action==='restore'){if(!b.versionId)throw new Error('Version ID is required.');return NextResponse.json({resume:await service.restoreVersion(owner,b.id,b.versionId)});}await service.deleteResume(owner,b.id);return NextResponse.json({ok:true});}catch(e){return apiError(e);}}
