import { ResumeData, SectionKey, sectionLabels } from '../resume';
import { getTemplate } from '../templates';
export function escapeLatex(text:string):string { return text.replace(/[\\{}$&#%_~^]/g,c=>({'\\':'\\textbackslash{}','{':'\\{','}':'\\}','$':'\\$','&':'\\&','#':'\\#','%':'\\%','_':'\\_','~':'\\textasciitilde{}','^':'\\textasciicircum{}'}[c]!)); }
export function safeUrl(value:string):string { try {const url = new URL(/^https?:\/\//i.test(value)?value:`https://${value}`);return ['http:','https:'].includes(url.protocol)?url.href:'';}catch{return '';}}
export function renderLatex(data:ResumeData,templateId:string):string {
 const t=getTemplate(templateId),p=data.personal,e=escapeLatex;
 const contact=[p.email,p.phone,p.location,p.linkedin,p.github,p.website].filter(Boolean).map(e).join(' $\\cdot$ ');
 const sections = [...new Set(data.sectionOrder)].filter(k=>k!=='personal').map((key:SectionKey)=>{
 if(key==='personal')return '';const value=data[key];if(!value || !value.length)return '';
 const title=`\\section*{${e(sectionLabels[key])}}`;
 if(typeof value==='string') return `${title}\n${e(value).replace(/\n/g,'\\\\\n')}`;
 if(!Array.isArray(value))return '';
 return `${title}\n`+value.map(item=>`\\noindent\\textbf{${e(item.title)}} \\hfill ${e([item.startDate,item.endDate].filter(Boolean).join(' -- '))}\\\\\n\\textit{${e(item.subtitle)}} \\hfill ${e(item.location)}\n${item.bullets.filter(Boolean).length?'\\begin{itemize}[leftmargin=*,nosep]\n'+item.bullets.filter(Boolean).map(b=>'\\item '+e(b)).join('\n')+'\n\\end{itemize}':''}\n${item.technologies?`\\noindent ${e(item.technologies)}\\\\`:''}\n${item.url&&safeUrl(item.url)?`\\noindent\\href{${e(safeUrl(item.url))}}{${e(item.url)}}\\\\`:''}\n\\vspace{5pt}`).join('\n');
 }).join('\n\n');
 return `% Generated by CVFlight — ${t.name}\n\\documentclass[${t.fontSize}pt,letterpaper]{article}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage[margin=${t.margin}in]{geometry}\n\\usepackage{enumitem,titlesec,xcolor}\n\\usepackage[hidelinks]{hyperref}\n\\definecolor{accent}{HTML}{${t.accent.slice(1)}}\n${t.font==='sans'?'\\usepackage{helvet}\n\\renewcommand{\\familydefault}{\\sfdefault}':''}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0pt}\n\\titleformat{\\section}{\\large\\bfseries\\color{accent}}{}{0em}{}[\\titlerule]\n\\titlespacing*{\\section}{0pt}{10pt}{5pt}\n\\begin{document}\n${t.header==='center'?'\\begin{center}':''}\n{\\LARGE\\bfseries ${e(p.firstName+' '+p.lastName)}}\\\\[4pt]\n${e(p.title)}\\\\[5pt]\n{\\small ${contact}}\n${t.header==='center'?'\\end{center}':''}\n${sections}\n\\end{document}\n`;
}
