import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { ResumeData, sectionLabels } from '../resume';
import { getTemplate } from '../templates';
export async function generatePDF(data:ResumeData,templateId:string){
 const doc=await PDFDocument.create(),t=getTemplate(templateId);doc.setTitle(`${data.personal.firstName} ${data.personal.lastName} — Resume`);doc.setCreator('CVFlight structured PDF renderer');
 const font=await doc.embedFont(t.font==='serif'?StandardFonts.TimesRoman:StandardFonts.Helvetica),bold=await doc.embedFont(t.font==='serif'?StandardFonts.TimesRomanBold:StandardFonts.HelveticaBold);
 let page=doc.addPage([612,792]),y=744;const margin=t.margin*72,width=612-margin*2;const accent=rgb(parseInt(t.accent.slice(1,3),16)/255,parseInt(t.accent.slice(3,5),16)/255,parseInt(t.accent.slice(5,7),16)/255);
 const clean=(s:string)=>s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[–—]/g,'-').replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/[^\x20-\x7e\n\u2022]/g,'?');
 function line(text:string,size=10,isBold=false,center=false){const f=isBold?bold:font;const words=clean(text).split(/\s+/);let buffer='';const lines:string[]=[];for(const word of words){if(f.widthOfTextAtSize((buffer?buffer+' ':'')+word,size)>width&&buffer){lines.push(buffer);buffer=word;}else buffer+=(buffer?' ':'')+word;}if(buffer)lines.push(buffer);for(const l of lines){if(y<margin+20){page=doc.addPage([612,792]);y=792-margin;}page.drawText(l,{x:center?Math.max(margin,(612-f.widthOfTextAtSize(l,size))/2):margin,y,size,font:f,color:rgb(.16,.16,.16),maxWidth:width});y-=size*1.38;}}
 const p=data.personal;line(`${p.firstName} ${p.lastName}`,24,true,t.header==='center');y-=3;line(p.title,11,false,t.header==='center');y-=4;line([p.email,p.phone,p.location].filter(Boolean).join('  |  '),8.5,false,t.header==='center');line([p.linkedin,p.github,p.website].filter(Boolean).join('  |  '),8,false,t.header==='center');y-=13;
 for(const key of [...new Set(data.sectionOrder)]){if(key==='personal')continue;const val=data[key];if(!val?.length)continue;if(y<margin+65){page=doc.addPage([612,792]);y=792-margin;}line(sectionLabels[key].toUpperCase(),10,true);page.drawLine({start:{x:margin,y:y+7},end:{x:612-margin,y:y+7},thickness:.5,color:accent});y-=4;if(typeof val==='string'){for(const l of val.split('\n'))line(l,t.fontSize);}else{for(const entry of val){line([entry.title,[entry.startDate,entry.endDate].filter(Boolean).join(' - ')].filter(Boolean).join('     |     '),10,true);if(entry.subtitle)line([entry.subtitle,entry.location].filter(Boolean).join('  |  '),9.5);for(const b of entry.bullets.filter(Boolean))line('•  '+b,9.5);if(entry.technologies)line(entry.technologies,9);if(entry.url)line(entry.url,8.5);y-=7;}}y-=9;}
 return {bytes:await doc.save(),pages:doc.getPageCount()};
}
